version: '3'
services:
    db:
        env_file: .env
        build: ./db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYROOT_PASS}
            TZ: "Asia/Tokyo"
        ports:
            - "3306:3306"
    app:
        build: ./app/
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true
networks:
    common_link:
        external: true